### ISSUE TITLE
Omeka S v4 support?

### ISSUE THREAD

**Issue by jlayt** [sinanatra/NestedDataTypes#17]
I've tried installing in a v4.0 Omeka S install, but the Modules page reports "Error: Nested Data Types requires Omeka S ^3.0.0". Do you plan to update with 4.0 support?

**Comment by RheRem12** [comment]
We would be interested in this update as well! This module would fix issues we have with using CIDOC-CRM in Omeka and it seems there is no alternative available.

**Comment by sinanatra** [comment]
Hi, I am not working much with Omeka S at the given time but can try to have a look. When I was working with CIDOC-CRM I was using the value annotations as alternative: https://omeka.org/s/docs/user-manual/content/items/#value-annotation. 

In the meantime please try to change the omeka_version_constraint in the module.ini in your local version, if it works I can update the repository https://github.com/sinanatra/NestedDataTypes/blob/master/config/module.ini

Thanks!

**Comment by PiaSpriensma** [comment]
Change the omeka_version_constraint works for us, after we also changed the namespace in Module.php. (There is missing a 's' at the end)

**Comment by RheRem12** [comment]
Unfortunately, we were able to install the module, but it caused Omeka S to show an error when trying to display items or item sets.  The error log states that an invalid abstract factory was registered. Any idea what could be causing this?

**Comment by jlayt** [comment]
I've submitted a Pull Request #18  to enable v4 support. I didn't find any breakages in my brief testing, I can test more fully if I can find a way to improve the performance.

**Comment by sablinavis** [comment]
> Change the omeka_version_constraint works for us, after we also changed the namespace in Module.php. (There is missing a 's' at the end)

No the s should not be added there, I found it easier to rename the module name instead.

**Comment by sinanatra** [comment]
Thanks @jlayt for the pull request 💪  I've tested and seem to work, I've renamed the repo removing the `s` to avoid the confusion @SVis760
